### ISSUE TITLE
Update the doc to tell last version support sonarqube >=10

### ISSUE THREAD

**Issue by mffrench** [C4tWithShell/community-rust#124]
Hello,

when installing on sonarqube v9.9.8 I got following error: 

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@66ac5762-org.sonar.server.plugins.ServerPluginManager': Initialization of bean failed; nested exception is Plugin Rust language analyzer [communityrust] requires at least Sonar Plugin API version 10.11.0.2468 (current: 9.14.0.375)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
```

I tested agains sonarqube 10.8 and it looks working better - at least sonarqube is able to start.

Probably should you update the [doc](https://github.com/C4tWithShell/community-rust/blob/master/DOC.md) to tell users it needs sonarqube 10.8 or higher ?

Best

**Comment by mffrench** [comment]
Closing the issue as the verison matrix is in the main README !
